["_vimrc"]
  type = "file"
  url  = "https://raw.githubusercontent.com/Honekatsu/.dotfiles/refs/heads/main/apps/.vimrc"
  refreshPeriod = "1m"

[".ssh/config"]
  type = "file"
  url  = "https://raw.githubusercontent.com/Honekatsu/.dotfiles/refs/heads/main/apps/ssh_config"
  refreshPeriod = "1m"

[".config/starship.toml"]
  type = "file"
  url  = "https://raw.githubusercontent.com/Honekatsu/.dotfiles/refs/heads/main/apps/zsh/starship.toml"
  refreshPeriod = "1m"